### ISSUE TITLE
Responsive image field don't work,click add button don't any action

### ISSUE THREAD

**Issue by effapp** [EtchUK/Etch.OrchardCore.Fields#128]
Responsive image field don't work,click add button don't any action

display error in console:

![image](https://github.com/EtchUK/Etch.OrchardCore.Fields/assets/51013754/4254fdfa-fa46-4e2c-8c75-70b7b6b1eea3)

**Comment by peterkeating** [comment]
This has been resolved in the [new version (1.7.0)](https://www.nuget.org/packages/Etch.OrchardCore.Fields/1.7.0).
